version: '3'
services:
  postgres:
    image: postgres
    restart: always
    expose:
      - '5432'
    volumes:
      - pg-db-data:/data/db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: 'redis:latest'
  api:
    expose:
      - '3030'
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - DB_TYPE=pg
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_URI=http://localhost:3030
      - UPLOADS_PUBLIC_URL=http://localhost:3030
    ports:
      - '3030:3030'
  dashboard:
    build:
      dockerfile: Dockerfile
      context: ./dashboard
      args:
        - REACT_APP_BASE_URL=http://localhost:3030/
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./dashboard:/app
    expose:
      - '3333'
    ports:
      - '80:3333'

volumes:
  pg-db-data:
